version: "3"

services:
  service_gateway:
    container_name: service_gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    env_file:
      - .env
    environment:
      - PORT=$GATEWAY_PORT
      - USER_SERVICE_IP=service_user
      - USER_SERVICE_PORT=$USER_SERVICE_PORT
      - ACTIVITY_SERVICE_IP=service_activity
      - ACTIVITY_SERVICE_PORT=$ACTIVITY_SERVICE_PORT
    build:
      dockerfile: ./packages/gateway_service/Dockerfile
      context: "."
    restart: always
    networks:
      - network

  service_user:
    container_name: service_user
    expose:
      - $USER_SERVICE_PORT
    environment:
      - PORT=$USER_SERVICE_PORT
      - ADDRESS_EMAIL=$ADDRESS_EMAIL
      - PASSWORD_EMAIL=$PASSWORD_EMAIL
      - SMTP_ADDRESS_EMAIL=$SMTP_ADDRESS_EMAIL
      - SMTP_PORT_EMAIL=$SMTP_PORT_EMAIL
      - DB_DIRECTORY=/app/db
      - DB_UNUSED_CLOSE_PERIOD=10
    build:
      dockerfile: ./packages/user_service/Dockerfile
      context: "."
    volumes:
      - user_db_data:/app/db
    restart: always
    networks:
      - network

  service_activity:
    container_name: service_activity
    expose:
      - $ACTIVITY_SERVICE_PORT
    environment:
      - PORT=$ACTIVITY_SERVICE_PORT
      - DB_DIRECTORY=/app/db
      - DB_UNUSED_CLOSE_PERIOD=10
    build:
      dockerfile: ./packages/activity_service/Dockerfile
      context: "."
    volumes:
      - service_activity_db_data:/app/db
    restart: always
    networks:
      - network

volumes:
  user_db_data: {}
  service_activity_db_data: {}

networks:
  network:
    driver: bridge
